#!/bin/sh
 
DEVCLASS=$1 
DEVNAME=$2 
 
case $DEVCLASS in 
2) 
	# disk devices 
	disklabel=`/sbin/disklabel $DEVNAME 2>&1 | sed -n '/^label: /s/^label: //p'` 
  duid=`/sbin/disklabel $DEVNAME 2>&1 | sed -n '/^duid: /s/^duid: //p'`
  grep -q $duid /etc/fstab && echo "Attempting to mount any partitions on $DEVNAME $duid: $disklabel"
  echo q  | /sbin/disklabel -E -F /dev/stderr $DEVNAME 2>&1 1> /dev/null | cut -d ' ' -f 1 | xargs -n 1 mount -v
	;; 
3) 
	# network devices; requires hostname.$DEVNAME 
	#sh /etc/netstart $DEVNAME 
	;; 
esac

